system_prompt: "You are an expert in payment classification. Answer the question directly."

classify_user_prompt: |
  Classify this payment transaction into the most suitable category, given all available information.
  Payment: {payment_text}
  Choose one most suitable category based on the available information.
  Available categories: {valid_categories}.

  Respond with a valid JSON object that contains:
  - "category": string (the classification category)
  - "reasoning": string (explanation for the classification)
  
  Example: {{"category": "groceries", "reasoning": "This is a food purchase"}}
  
  Respond only with the JSON object.

classify_user_prompt_with_search: |
  Classify this payment transaction into the most suitable category, given all available information.
  Payment: {payment_text}
  Choose one most suitable category based on the available information.
  Available categories: {valid_categories}.
  
  Additional context from web search:
  {search_results}
  
  Use the search results to better understand the payment if needed, but classify based on the payment text and available categories.
  
  Respond with a valid JSON object that contains:
  - "category": string (the classification category)
  - "reasoning": string (explanation for the classification)
  
  Example: {{"category": "groceries", "reasoning": "This is a food purchase based on the search results"}}
  
  Respond only with the JSON object.

ollama_json_instruction: |
  You must respond with a valid JSON object that contains the actual classification data, not the schema definition. 

  The JSON should have these fields:
  - "category": string (the classification category)
  - "reasoning": string (explanation for the classification)
  - "search_used": boolean (whether search was used)

  Example response format:
  {{"category": "groceries", "reasoning": "This is a food purchase", "search_used": false}}

  Respond only with the JSON object containing the actual data, no schema definition or additional text.